#pragma once

/* THIS FILE IS AUTOGENERATED */

#include "base/str.h"

enum g_ui {
  G_UI_NONE = 0,

  G_UI_ACCEPT,
  G_UI_BACK,
  G_UI_LEFT,
  G_UI_RIGHT,
  G_UI_UP,
  G_UI_DOWN,

  G_UI_NUM_COUNT,
};


static const str8 G_UI_LABELS[G_UI_NUM_COUNT] = {
  [G_UI_NONE] = str8_lit_comp("NONE"),
  [G_UI_ACCEPT] = str8_lit_comp("ACCEPT"),
  [G_UI_BACK] = str8_lit_comp("BACK"),
  [G_UI_LEFT] = str8_lit_comp("LEFT"),
  [G_UI_RIGHT] = str8_lit_comp("RIGHT"),
  [G_UI_UP] = str8_lit_comp("UP"),
  [G_UI_DOWN] = str8_lit_comp("DOWN"),
};

