#pragma once

/* THIS FILE IS AUTOGENERATED */

#include "base/str.h"

enum game_theme {
  GAME_THEME_NONE = 0,

  GAME_THEME_SHAPES,
  GAME_THEME_SEEDS,
  GAME_THEME_ABSTRACT,

  GAME_THEME_NUM_COUNT,
};


static const str8 GAME_THEME_LABELS[GAME_THEME_NUM_COUNT] = {
  [GAME_THEME_NONE] = str8_lit_comp("NONE"),
  [GAME_THEME_SHAPES] = str8_lit_comp("SHAPES"),
  [GAME_THEME_SEEDS] = str8_lit_comp("SEEDS"),
  [GAME_THEME_ABSTRACT] = str8_lit_comp("ABSTRACT"),
};

