#pragma once

/* THIS FILE IS AUTOGENERATED */

#include "base/str.h"

enum scrn_game_state {
  SCRN_GAME_STATE_NONE = 0,

  SCRN_GAME_STATE_PLAY,
  SCRN_GAME_STATE_COLLPASE,
  SCRN_GAME_STATE_PAUSE,
  SCRN_GAME_STATE_OVER,

  SCRN_GAME_STATE_NUM_COUNT,
};


static const str8 SCRN_GAME_STATE_LABELS[SCRN_GAME_STATE_NUM_COUNT] = {
  [SCRN_GAME_STATE_NONE] = str8_lit_comp("NONE"),
  [SCRN_GAME_STATE_PLAY] = str8_lit_comp("PLAY"),
  [SCRN_GAME_STATE_COLLPASE] = str8_lit_comp("COLLPASE"),
  [SCRN_GAME_STATE_PAUSE] = str8_lit_comp("PAUSE"),
  [SCRN_GAME_STATE_OVER] = str8_lit_comp("OVER"),
};

