#pragma once

/* THIS FILE IS AUTOGENERATED */

#include "base/str.h"
#include "base/types.h"

enum block_type {
  BLOCK_TYPE_NONE = 0,

  BLOCK_TYPE_A,
  BLOCK_TYPE_B,
  BLOCK_TYPE_C,
  BLOCK_TYPE_D,
  BLOCK_TYPE_E,
  BLOCK_TYPE_F,

  BLOCK_TYPE_NUM_COUNT,
};


static const str8 BLOCK_TYPE_LABELS[BLOCK_TYPE_NUM_COUNT] = {
  [BLOCK_TYPE_NONE] = str8_lit_comp("NONE"),
  [BLOCK_TYPE_A] = str8_lit_comp("A"),
  [BLOCK_TYPE_B] = str8_lit_comp("B"),
  [BLOCK_TYPE_C] = str8_lit_comp("C"),
  [BLOCK_TYPE_D] = str8_lit_comp("D"),
  [BLOCK_TYPE_E] = str8_lit_comp("E"),
  [BLOCK_TYPE_F] = str8_lit_comp("F"),
};

static u8 BLOCK_TYPE_BITMASKS[7] = {
  [BLOCK_TYPE_NONE] = 0,
  [BLOCK_TYPE_A] = 2,
  [BLOCK_TYPE_B] = 4,
  [BLOCK_TYPE_C] = 8,
  [BLOCK_TYPE_D] = 16,
  [BLOCK_TYPE_E] = 32,
  [BLOCK_TYPE_F] = 64,
};

