#pragma once

/* THIS FILE IS AUTOGENERATED */

#include "base/str.h"

enum board_state {
  BOARD_STATE_NONE = 0,

  BOARD_STATE_PIECE,
  BOARD_STATE_COLLPASE,
  BOARD_STATE_OVER,

  BOARD_STATE_NUM_COUNT,
};


static const str8 BOARD_STATE_LABELS[BOARD_STATE_NUM_COUNT] = {
  [BOARD_STATE_NONE] = str8_lit_comp("NONE"),
  [BOARD_STATE_PIECE] = str8_lit_comp("PIECE"),
  [BOARD_STATE_COLLPASE] = str8_lit_comp("COLLPASE"),
  [BOARD_STATE_OVER] = str8_lit_comp("OVER"),
};

